import java.lang.reflect.Field;
import org.eclipse.jdt.core.compiler.IProblem;


public class ProblemIdToJson {

	public static void main(String [  ] args){
		Field[] interfaceFields=IProblem.class.getFields();
		String output = "/**\n";
			output += "* This is an auto generated file from the IProblem problem marker class from eclipse.\n";
			output += "* It is generated by the LAProcessor utility ProblemIdToJson. \n";
			output += "**/\n\n";
			output += "var categoryIdToDescription = {\n";

		String fields = "";

		for(Field f:interfaceFields) {
			try{

			String name = f.getName();
			int val = f.getInt(null);
			fields += "'"+val+"': '"+name+"',\n";

			}catch(Exception e){
				System.out.println("Exception");
			}
		}
		output += fields.substring(0, fields.length()-2);
		output += "}\n\n";


		String generalCategories = "var generalCategories = [";
		generalCategories += "'TypeRelated', 'FieldRelated', 'MethodRelated', 'ConstructorRelated', 'ImportRelated', 'Internal', 'Syntax', 'Javadoc'";
		generalCategories += "]\n\n";

		output += generalCategories;

		output += "module.exports = {categoryIdToDescription: categoryIdToDescription, generalCategories: generalCategories}";

		System.out.println(output);
	}

}
